sudo: true
dist: trusty
language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_install:
  - echo "y" | sdkmanager "cmake;3.6.4111459"
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk
  - export ANDROID_NDK_HOME=$HOME/android-ndk

script:
  - ./gradlew :app:assembleRelease
  
after_success:
  - find ./ -name "*.apk"

deploy: 
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - ../app/build/outputs/apk/release/app-release-unsigned.apk
  skip_cleanup: true
